"""empty message

Revision ID: 131eab90f87e
Revises: 5aa420ea0c63
Create Date: 2025-07-13 19:54:47.877929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131eab90f87e'
down_revision = '5aa420ea0c63'
branch_labels = None
depends_on = None

gender_enum = sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_enum')


def upgrade():
    # Create enum type explicitly
    gender_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', gender_enum, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
    # Drop the enum type
    gender_enum.drop(op.get_bind(), checkfirst=True)
