"""empty message

Revision ID: 156c3d41a8f5
Revises: acb6db6f1a34
Create Date: 2024-04-15 14:09:01.821525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156c3d41a8f5'
down_revision = 'acb6db6f1a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_service_association')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_id')

    op.create_table('appointment_service_association',
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='appointment_service_association_appointment_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='appointment_service_association_service_id_fkey')
    )
    # ### end Alembic commands ###
