"""empty message

Revision ID: 223159170c1e
Revises: b642746e0844
Create Date: 2024-03-25 11:16:01.246299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223159170c1e'
down_revision = 'b642746e0844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(), nullable=True))

    with op.batch_alter_table('clientsnotitications', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientsnotitications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###
