"""empty message

Revision ID: 2605fd0e01c1
Revises: ca4fdcdfcba8
Create Date: 2024-07-08 21:37:42.347077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2605fd0e01c1'
down_revision = 'ca4fdcdfcba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('profile_image')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
