"""empty message

Revision ID: 2c1e98095e7f
Revises: 7f0326018217
Create Date: 2024-04-29 14:20:06.936026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1e98095e7f'
down_revision = '7f0326018217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments_services_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('services_businesses_association')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('appointments_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Integer(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_categories', ['category'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category')
        batch_op.drop_column('price')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('average_rating')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('appointments_service_id_fkey', 'services', ['service_id'], ['id'], ondelete='SET NULL')

    op.create_table('services_businesses_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('specific_service', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='services_businesses_association_business_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='services_businesses_association_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='services_businesses_association_pkey')
    )
    op.drop_table('appointments_services_association')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
