"""empty message

Revision ID: 30e7e0e91218
Revises: 0fd38ca80f3a
Create Date: 2024-03-17 02:40:41.622800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e7e0e91218'
down_revision = '0fd38ca80f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_businesses_association',
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_businesses_association')
    # ### end Alembic commands ###
