"""empty message

Revision ID: 365f79fdf161
Revises: 186b6377eeff
Create Date: 2024-05-17 11:42:09.651392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365f79fdf161'
down_revision = '186b6377eeff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businessgallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businessgallery')
    # ### end Alembic commands ###
