"""empty message

Revision ID: 6239e4a6e89e
Revises: d5ba0e466fd8
Create Date: 2024-05-14 16:28:13.648231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6239e4a6e89e'
down_revision = 'd5ba0e466fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_mode', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('notification_mode')

    # ### end Alembic commands ###
