"""empty message

Revision ID: 70959812d33d
Revises: 94330344861b
Create Date: 2024-03-14 00:49:54.534944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70959812d33d'
down_revision = '94330344861b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
