"""empty message

Revision ID: 989202fec81a
Revises: 0f406d2da692
Create Date: 2024-04-17 08:58:32.755151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989202fec81a'
down_revision = '0f406d2da692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientsdeleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientsdeleted')
    # ### end Alembic commands ###
