"""empty message

Revision ID: b234d6812700
Revises: 989202fec81a
Create Date: 2024-04-17 12:50:04.388348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b234d6812700'
down_revision = '989202fec81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientsdeleted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientsdeleted', schema=None) as batch_op:
        batch_op.drop_column('request_date')

    # ### end Alembic commands ###
