"""empty message

Revision ID: b98dd97b7d01
Revises: f3faadf8bde5
Create Date: 2024-05-06 12:29:21.596081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98dd97b7d01'
down_revision = 'f3faadf8bde5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments_services_association')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_id')

    op.create_table('appointments_services_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='appointments_services_association_appointment_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='appointments_services_association_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='appointments_services_association_pkey')
    )
    # ### end Alembic commands ###
