"""empty message

Revision ID: ca4fdcdfcba8
Revises: 365f79fdf161
Create Date: 2024-05-17 12:20:24.342078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4fdcdfcba8'
down_revision = '365f79fdf161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businessgallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businessgallery', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
