"""empty message

Revision ID: ca9a239decb9
Revises: a767b42f5bb1
Create Date: 2024-04-29 22:10:59.686966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca9a239decb9'
down_revision = 'a767b42f5bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('weekend_opening',
               existing_type=postgresql.TIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('weekend_closing',
               existing_type=postgresql.TIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('weekday_opening',
               existing_type=postgresql.TIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('weekday_closing',
               existing_type=postgresql.TIME(),
               type_=sa.Time(),
               existing_nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('clients_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint('clients_phone_key', ['phone'])

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('weekday_closing',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('weekday_opening',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('weekend_closing',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('weekend_opening',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
