"""empty message

Revision ID: d5ba0e466fd8
Revises: b98dd97b7d01
Create Date: 2024-05-13 12:38:00.689067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ba0e466fd8'
down_revision = 'b98dd97b7d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('l_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('l_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
