"""empty message

Revision ID: fa7a08fec1f9
Revises: 84d99ca5055a
Create Date: 2025-04-26 16:46:46.366210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7a08fec1f9'
down_revision = '84d99ca5055a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('formatted_address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('google_map')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_map', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('formatted_address')
        batch_op.drop_column('place_id')

    # ### end Alembic commands ###
